<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1c61ec16f12f94d63c43e36f95f8b328
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'LINE\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LINE\\' => 
        array (
            0 => __DIR__ . '/..' . '/linecorp/line-bot-sdk/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1c61ec16f12f94d63c43e36f95f8b328::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1c61ec16f12f94d63c43e36f95f8b328::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
